use std::error::Error;

mod task;
mod datetime;

fn main() -> Result<(), Box<dyn Error>> {
  Ok(())
}
